# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_prev', [dirname(__file__)])
        except ImportError:
            import _prev
            return _prev
        if fp is not None:
            try:
                _mod = imp.load_module('_prev', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _prev = swig_import_helper()
    del swig_import_helper
else:
    import _prev
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _prev.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _prev.SwigPyIterator_value(self)
    def incr(self, n=1): return _prev.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _prev.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _prev.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _prev.SwigPyIterator_equal(self, *args)
    def copy(self): return _prev.SwigPyIterator_copy(self)
    def next(self): return _prev.SwigPyIterator_next(self)
    def __next__(self): return _prev.SwigPyIterator___next__(self)
    def previous(self): return _prev.SwigPyIterator_previous(self)
    def advance(self, *args): return _prev.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _prev.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _prev.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _prev.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _prev.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _prev.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _prev.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _prev.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


def findPrev(*args):
  return _prev.findPrev(*args)
findPrev = _prev.findPrev
class vec(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vec, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vec, name)
    __repr__ = _swig_repr
    def iterator(self): return _prev.vec_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _prev.vec___nonzero__(self)
    def __bool__(self): return _prev.vec___bool__(self)
    def __len__(self): return _prev.vec___len__(self)
    def pop(self): return _prev.vec_pop(self)
    def __getslice__(self, *args): return _prev.vec___getslice__(self, *args)
    def __setslice__(self, *args): return _prev.vec___setslice__(self, *args)
    def __delslice__(self, *args): return _prev.vec___delslice__(self, *args)
    def __delitem__(self, *args): return _prev.vec___delitem__(self, *args)
    def __getitem__(self, *args): return _prev.vec___getitem__(self, *args)
    def __setitem__(self, *args): return _prev.vec___setitem__(self, *args)
    def append(self, *args): return _prev.vec_append(self, *args)
    def empty(self): return _prev.vec_empty(self)
    def size(self): return _prev.vec_size(self)
    def clear(self): return _prev.vec_clear(self)
    def swap(self, *args): return _prev.vec_swap(self, *args)
    def get_allocator(self): return _prev.vec_get_allocator(self)
    def begin(self): return _prev.vec_begin(self)
    def end(self): return _prev.vec_end(self)
    def rbegin(self): return _prev.vec_rbegin(self)
    def rend(self): return _prev.vec_rend(self)
    def pop_back(self): return _prev.vec_pop_back(self)
    def erase(self, *args): return _prev.vec_erase(self, *args)
    def __init__(self, *args): 
        this = _prev.new_vec(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _prev.vec_push_back(self, *args)
    def front(self): return _prev.vec_front(self)
    def back(self): return _prev.vec_back(self)
    def assign(self, *args): return _prev.vec_assign(self, *args)
    def resize(self, *args): return _prev.vec_resize(self, *args)
    def insert(self, *args): return _prev.vec_insert(self, *args)
    def reserve(self, *args): return _prev.vec_reserve(self, *args)
    def capacity(self): return _prev.vec_capacity(self)
    __swig_destroy__ = _prev.delete_vec
    __del__ = lambda self : None;
vec_swigregister = _prev.vec_swigregister
vec_swigregister(vec)

class dvec(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, dvec, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, dvec, name)
    __repr__ = _swig_repr
    def iterator(self): return _prev.dvec_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _prev.dvec___nonzero__(self)
    def __bool__(self): return _prev.dvec___bool__(self)
    def __len__(self): return _prev.dvec___len__(self)
    def pop(self): return _prev.dvec_pop(self)
    def __getslice__(self, *args): return _prev.dvec___getslice__(self, *args)
    def __setslice__(self, *args): return _prev.dvec___setslice__(self, *args)
    def __delslice__(self, *args): return _prev.dvec___delslice__(self, *args)
    def __delitem__(self, *args): return _prev.dvec___delitem__(self, *args)
    def __getitem__(self, *args): return _prev.dvec___getitem__(self, *args)
    def __setitem__(self, *args): return _prev.dvec___setitem__(self, *args)
    def append(self, *args): return _prev.dvec_append(self, *args)
    def empty(self): return _prev.dvec_empty(self)
    def size(self): return _prev.dvec_size(self)
    def clear(self): return _prev.dvec_clear(self)
    def swap(self, *args): return _prev.dvec_swap(self, *args)
    def get_allocator(self): return _prev.dvec_get_allocator(self)
    def begin(self): return _prev.dvec_begin(self)
    def end(self): return _prev.dvec_end(self)
    def rbegin(self): return _prev.dvec_rbegin(self)
    def rend(self): return _prev.dvec_rend(self)
    def pop_back(self): return _prev.dvec_pop_back(self)
    def erase(self, *args): return _prev.dvec_erase(self, *args)
    def __init__(self, *args): 
        this = _prev.new_dvec(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _prev.dvec_push_back(self, *args)
    def front(self): return _prev.dvec_front(self)
    def back(self): return _prev.dvec_back(self)
    def assign(self, *args): return _prev.dvec_assign(self, *args)
    def resize(self, *args): return _prev.dvec_resize(self, *args)
    def insert(self, *args): return _prev.dvec_insert(self, *args)
    def reserve(self, *args): return _prev.dvec_reserve(self, *args)
    def capacity(self): return _prev.dvec_capacity(self)
    __swig_destroy__ = _prev.delete_dvec
    __del__ = lambda self : None;
dvec_swigregister = _prev.dvec_swigregister
dvec_swigregister(dvec)

# This file is compatible with both classic and new-style classes.


